global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'harmonydb'
    static_configs:
      - targets: ['node1:8081', 'node2:8082', 'node3:8083']
        labels:
          cluster: 'harmonydb-cluster'
